INSERT INTO USUARIO (NOME, EMAIL, SENHA, ROLE)
SELECT 'Administrador', 'admin@duckbill.com',
       '$2b$12$w.XTV4xQznhGm35OtO1gWeQ2FMHMw7i1kYtxO8xJ/cI/aJF86UQj6', 'ROLE_ADMIN'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM USUARIO WHERE EMAIL = 'admin@duckbill.com');

INSERT INTO USUARIO (NOME, EMAIL, SENHA, ROLE)
SELECT 'Usuário Padrão', 'user@duckbill.com',
       '$2b$12$90JwylOQgDovkrVbw79SG.a89DXHovSxWjg6VXfjNf52VOV8e8pJm', 'ROLE_USER'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM USUARIO WHERE EMAIL = 'user@duckbill.com');

INSERT INTO CATEGORIA (NOME)
SELECT 'Alimentação' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE NOME = 'Alimentação');
INSERT INTO CATEGORIA (NOME)
SELECT 'Transporte' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE NOME = 'Transporte');
INSERT INTO CATEGORIA (NOME)
SELECT 'Moradia' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE NOME = 'Moradia');
INSERT INTO CATEGORIA (NOME)
SELECT 'Lazer' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE NOME = 'Lazer');
INSERT INTO CATEGORIA (NOME)
SELECT 'Saúde' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE NOME = 'Saúde');
INSERT INTO CATEGORIA (NOME)
SELECT 'Educação' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE NOME = 'Educação');

INSERT INTO ATIVO (TICKER, TIPO, MOEDA_BASE)
SELECT 'PETR4', 'STOCK', 'BRL' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM ATIVO WHERE TICKER = 'PETR4');
INSERT INTO ATIVO (TICKER, TIPO, MOEDA_BASE)
SELECT 'ITUB4', 'STOCK', 'BRL' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM ATIVO WHERE TICKER = 'ITUB4');
INSERT INTO ATIVO (TICKER, TIPO, MOEDA_BASE)
SELECT 'BOVA11', 'FUND', 'BRL' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM ATIVO WHERE TICKER = 'BOVA11');

INSERT INTO DESPESA (USUARIO_ID, CATEGORIA_ID, VALOR, MOEDA, DATA_COMPRA, DESCRICAO)
SELECT u.id, c.id, 85.50, 'BRL', TO_DATE('2026-03-01','YYYY-MM-DD'), 'Mercado'
FROM dual
JOIN USUARIO u ON u.email = 'user@duckbill.com'
JOIN CATEGORIA c ON c.nome = 'Alimentação'
WHERE NOT EXISTS (
    SELECT 1 FROM DESPESA d
    WHERE d.usuario_id = u.id
      AND d.categoria_id = c.id
      AND d.data_compra = TO_DATE('2026-03-01','YYYY-MM-DD')
      AND d.valor = 85.50
);
INSERT INTO DESPESA (USUARIO_ID, CATEGORIA_ID, VALOR, MOEDA, DATA_COMPRA, DESCRICAO)
SELECT u.id, c.id, 45.00, 'BRL', TO_DATE('2026-03-02','YYYY-MM-DD'), 'Transporte app'
FROM dual
JOIN USUARIO u ON u.email = 'user@duckbill.com'
JOIN CATEGORIA c ON c.nome = 'Transporte'
WHERE NOT EXISTS (
    SELECT 1 FROM DESPESA d
    WHERE d.usuario_id = u.id
      AND d.categoria_id = c.id
      AND d.data_compra = TO_DATE('2026-03-02','YYYY-MM-DD')
      AND d.valor = 45.00
);
INSERT INTO DESPESA (USUARIO_ID, CATEGORIA_ID, VALOR, MOEDA, DATA_COMPRA, DESCRICAO)
SELECT u.id, c.id, 120.00, 'BRL', TO_DATE('2026-03-02','YYYY-MM-DD'), 'Cinema'
FROM dual
JOIN USUARIO u ON u.email = 'user@duckbill.com'
JOIN CATEGORIA c ON c.nome = 'Lazer'
WHERE NOT EXISTS (
    SELECT 1 FROM DESPESA d
    WHERE d.usuario_id = u.id
      AND d.categoria_id = c.id
      AND d.data_compra = TO_DATE('2026-03-02','YYYY-MM-DD')
      AND d.valor = 120.00
);
INSERT INTO DESPESA (USUARIO_ID, CATEGORIA_ID, VALOR, MOEDA, DATA_COMPRA, DESCRICAO)
SELECT u.id, c.id, 950.00, 'BRL', TO_DATE('2026-03-03','YYYY-MM-DD'), 'Aluguel'
FROM dual
JOIN USUARIO u ON u.email = 'user@duckbill.com'
JOIN CATEGORIA c ON c.nome = 'Moradia'
WHERE NOT EXISTS (
    SELECT 1 FROM DESPESA d
    WHERE d.usuario_id = u.id
      AND d.categoria_id = c.id
      AND d.data_compra = TO_DATE('2026-03-03','YYYY-MM-DD')
      AND d.valor = 950.00
);

INSERT INTO TRANSACAO_ATIVO (USUARIO_ID, ATIVO_ID, TIPO, QTD, PRECO, DATA_NEGOCIO)
SELECT u.id, a.id, 'BUY', 10.0000, 32.450000, TO_DATE('2026-03-02','YYYY-MM-DD')
FROM dual
JOIN USUARIO u ON u.email = 'user@duckbill.com'
JOIN ATIVO a ON a.ticker = 'PETR4'
WHERE NOT EXISTS (
    SELECT 1 FROM TRANSACAO_ATIVO t
    WHERE t.usuario_id = u.id
      AND t.ativo_id = a.id
      AND t.tipo = 'BUY'
      AND t.qtd = 10.0000
      AND t.preco = 32.450000
      AND t.data_negocio = TO_DATE('2026-03-02','YYYY-MM-DD')
);
