DECLARE
  PROCEDURE sync_identity(p_table VARCHAR2) IS
    v_max_id NUMBER;
    v_has_id NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_has_id
      FROM user_tab_identity_cols
     WHERE table_name = UPPER(p_table)
       AND column_name = 'ID';

    IF v_has_id = 0 THEN
      RETURN;
    END IF;

    EXECUTE IMMEDIATE 'SELECT NVL(MAX(id),0) FROM ' || p_table INTO v_max_id;

    EXECUTE IMMEDIATE
      'ALTER TABLE ' || p_table ||
      ' MODIFY (ID GENERATED BY DEFAULT AS IDENTITY (START WITH ' || (v_max_id + 1) || '))';
  END;
BEGIN
  sync_identity('USUARIO');
  sync_identity('CATEGORIA');
  sync_identity('ATIVO');
  sync_identity('DESPESA');
  sync_identity('TRANSACAO_ATIVO');
END;
/
