ALTER TABLE USUARIO ADD SALDO NUMBER(12,2) DEFAULT 0 NOT NULL;

UPDATE USUARIO
SET SALDO = 0
WHERE SALDO IS NULL;

UPDATE USUARIO
SET SALDO = 2500.00
WHERE EMAIL = 'user@duckbill.com'
  AND SALDO = 0;

UPDATE USUARIO
SET SALDO = 5000.00
WHERE EMAIL = 'admin@duckbill.com'
  AND SALDO = 0;
